#!/usr/bin/env python
# -*- encoding: utf-8 -*-

# Form implementation generated from reading ui file 'User_interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import subprocess
import os.path

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IRTempus(object):
    def setupUi(self, IRTempus):
        IRTempus.setObjectName(_fromUtf8("IRTempus"))
        IRTempus.setWindowModality(QtCore.Qt.ApplicationModal)
        IRTempus.resize(852, 596)
        IRTempus.setWindowIcon(QtGui.QIcon('icon.ico')) 
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IRTempus.sizePolicy().hasHeightForWidth())
        IRTempus.setSizePolicy(sizePolicy)
        IRTempus.setAcceptDrops(False)
        IRTempus.setAutoFillBackground(False)
        IRTempus.setModal(True)
        self.tabPrincipal = QtGui.QTabWidget(IRTempus)
        self.tabPrincipal.setGeometry(QtCore.QRect(6, 7, 861, 581))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabPrincipal.sizePolicy().hasHeightForWidth())
        self.tabPrincipal.setSizePolicy(sizePolicy)
        self.tabPrincipal.setObjectName(_fromUtf8("tabPrincipal"))
        self.tab_mostrador = QtGui.QWidget()
        self.tab_mostrador.setObjectName(_fromUtf8("tab_mostrador"))
        self.pB_startacq = QtGui.QPushButton(self.tab_mostrador)
        self.pB_startacq.setGeometry(QtCore.QRect(520, 500, 141, 41))
        self.pB_startacq.setObjectName(_fromUtf8("pB_startacq"))
        self.l_mostrador = QtGui.QLabel(self.tab_mostrador)
        self.l_mostrador.setGeometry(QtCore.QRect(180, 505, 111, 31))
        self.l_mostrador.setObjectName(_fromUtf8("l_mostrador"))
        self.label_7 = QtGui.QLabel(self.tab_mostrador)
        self.label_7.setGeometry(QtCore.QRect(10, 510, 161, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.vS_channel_1 = QtGui.QSlider(self.tab_mostrador)
        self.vS_channel_1.setGeometry(QtCore.QRect(758, 27, 29, 61))
        self.vS_channel_1.setMaximum(1023)
        self.vS_channel_1.setProperty("value", 512)
        self.vS_channel_1.setTracking(True)
        self.vS_channel_1.setOrientation(QtCore.Qt.Vertical)
        self.vS_channel_1.setObjectName(_fromUtf8("vS_channel_1"))
        self.lE_channel_1 = QtGui.QLineEdit(self.tab_mostrador)
        self.lE_channel_1.setGeometry(QtCore.QRect(788, 47, 41, 27))
        self.lE_channel_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_channel_1.setObjectName(_fromUtf8("lE_channel_1"))
        self.vS_channel_2 = QtGui.QSlider(self.tab_mostrador)
        self.vS_channel_2.setGeometry(QtCore.QRect(758, 107, 29, 61))
        self.vS_channel_2.setMaximum(1023)
        self.vS_channel_2.setProperty("value", 512)
        self.vS_channel_2.setSliderPosition(512)
        self.vS_channel_2.setOrientation(QtCore.Qt.Vertical)
        self.vS_channel_2.setObjectName(_fromUtf8("vS_channel_2"))
        self.lE_channel_2 = QtGui.QLineEdit(self.tab_mostrador)
        self.lE_channel_2.setGeometry(QtCore.QRect(788, 127, 41, 27))
        self.lE_channel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_channel_2.setObjectName(_fromUtf8("lE_channel_2"))
        self.lE_channel_5 = QtGui.QLineEdit(self.tab_mostrador)
        self.lE_channel_5.setGeometry(QtCore.QRect(788, 367, 41, 27))
        self.lE_channel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_channel_5.setObjectName(_fromUtf8("lE_channel_5"))
        self.lE_channel_4 = QtGui.QLineEdit(self.tab_mostrador)
        self.lE_channel_4.setGeometry(QtCore.QRect(788, 287, 41, 27))
        self.lE_channel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_channel_4.setObjectName(_fromUtf8("lE_channel_4"))
        self.lE_channel_3 = QtGui.QLineEdit(self.tab_mostrador)
        self.lE_channel_3.setGeometry(QtCore.QRect(788, 207, 41, 27))
        self.lE_channel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_channel_3.setObjectName(_fromUtf8("lE_channel_3"))
        self.lE_channel_6 = QtGui.QLineEdit(self.tab_mostrador)
        self.lE_channel_6.setGeometry(QtCore.QRect(788, 447, 41, 27))
        self.lE_channel_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_channel_6.setObjectName(_fromUtf8("lE_channel_6"))
        self.vS_channel_4 = QtGui.QSlider(self.tab_mostrador)
        self.vS_channel_4.setGeometry(QtCore.QRect(758, 267, 29, 61))
        self.vS_channel_4.setMaximum(1023)
        self.vS_channel_4.setProperty("value", 512)
        self.vS_channel_4.setOrientation(QtCore.Qt.Vertical)
        self.vS_channel_4.setObjectName(_fromUtf8("vS_channel_4"))
        self.vS_channel_3 = QtGui.QSlider(self.tab_mostrador)
        self.vS_channel_3.setGeometry(QtCore.QRect(758, 187, 29, 61))
        self.vS_channel_3.setMaximum(1023)
        self.vS_channel_3.setProperty("value", 512)
        self.vS_channel_3.setOrientation(QtCore.Qt.Vertical)
        self.vS_channel_3.setObjectName(_fromUtf8("vS_channel_3"))
        self.vS_channel_5 = QtGui.QSlider(self.tab_mostrador)
        self.vS_channel_5.setGeometry(QtCore.QRect(758, 347, 29, 61))
        self.vS_channel_5.setMaximum(1023)
        self.vS_channel_5.setProperty("value", 512)
        self.vS_channel_5.setOrientation(QtCore.Qt.Vertical)
        self.vS_channel_5.setObjectName(_fromUtf8("vS_channel_5"))
        self.vS_channel_6 = QtGui.QSlider(self.tab_mostrador)
        self.vS_channel_6.setGeometry(QtCore.QRect(758, 427, 29, 61))
        self.vS_channel_6.setMaximum(1023)
        self.vS_channel_6.setProperty("value", 512)
        self.vS_channel_6.setOrientation(QtCore.Qt.Vertical)
        self.vS_channel_6.setObjectName(_fromUtf8("vS_channel_6"))
        self.tab_views = QtGui.QTabWidget(self.tab_mostrador)
        self.tab_views.setGeometry(QtCore.QRect(2, 3, 751, 491))
        self.tab_views.setTabPosition(QtGui.QTabWidget.West)
        self.tab_views.setObjectName(_fromUtf8("tab_views"))
        self.tab_separados = QtGui.QWidget()
        self.tab_separados.setObjectName(_fromUtf8("tab_separados"))
        self.pW_channel_5 = PlotWidget(self.tab_separados)
        self.pW_channel_5.setGeometry(QtCore.QRect(8, 349, 701, 51))
        self.pW_channel_5.setObjectName(_fromUtf8("pW_channel_5"))
        self.pW_channel_3 = PlotWidget(self.tab_separados)
        self.pW_channel_3.setGeometry(QtCore.QRect(8, 189, 701, 51))
        self.pW_channel_3.setObjectName(_fromUtf8("pW_channel_3"))
        self.sP_channel_4 = QtGui.QSpinBox(self.tab_separados)
        self.sP_channel_4.setGeometry(QtCore.QRect(78, 246, 61, 21))
        self.sP_channel_4.setMinimum(1)
        self.sP_channel_4.setObjectName(_fromUtf8("sP_channel_4"))
        self.lE_time_1 = QtGui.QLineEdit(self.tab_separados)
        self.lE_time_1.setGeometry(QtCore.QRect(148, 5, 81, 21))
        self.lE_time_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_time_1.setObjectName(_fromUtf8("lE_time_1"))
        self.sP_channel_2 = QtGui.QSpinBox(self.tab_separados)
        self.sP_channel_2.setGeometry(QtCore.QRect(79, 86, 61, 21))
        self.sP_channel_2.setMinimum(1)
        self.sP_channel_2.setObjectName(_fromUtf8("sP_channel_2"))
        self.lE_time_5 = QtGui.QLineEdit(self.tab_separados)
        self.lE_time_5.setGeometry(QtCore.QRect(148, 325, 81, 21))
        self.lE_time_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_time_5.setObjectName(_fromUtf8("lE_time_5"))
        self.cB_subida_4 = QtGui.QCheckBox(self.tab_separados)
        self.cB_subida_4.setGeometry(QtCore.QRect(350, 246, 100, 22))
        self.cB_subida_4.setChecked(True)
        self.cB_subida_4.setObjectName(_fromUtf8("cB_subida_4"))
        self.pW_channel_4 = PlotWidget(self.tab_separados)
        self.pW_channel_4.setGeometry(QtCore.QRect(8, 269, 701, 51))
        self.pW_channel_4.setObjectName(_fromUtf8("pW_channel_4"))
        self.cB_descida_2 = QtGui.QCheckBox(self.tab_separados)
        self.cB_descida_2.setGeometry(QtCore.QRect(460, 86, 100, 22))
        self.cB_descida_2.setObjectName(_fromUtf8("cB_descida_2"))
        self.l_channel_8 = QtGui.QLabel(self.tab_separados)
        self.l_channel_8.setGeometry(QtCore.QRect(230, 10, 70, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_channel_8.setFont(font)
        self.l_channel_8.setObjectName(_fromUtf8("l_channel_8"))
        self.sP_channel_3 = QtGui.QSpinBox(self.tab_separados)
        self.sP_channel_3.setGeometry(QtCore.QRect(79, 166, 61, 21))
        self.sP_channel_3.setMinimum(1)
        self.sP_channel_3.setObjectName(_fromUtf8("sP_channel_3"))
        self.l_channel_12 = QtGui.QLabel(self.tab_separados)
        self.l_channel_12.setGeometry(QtCore.QRect(232, 410, 70, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_channel_12.setFont(font)
        self.l_channel_12.setObjectName(_fromUtf8("l_channel_12"))
        self.l_channel_9 = QtGui.QLabel(self.tab_separados)
        self.l_channel_9.setGeometry(QtCore.QRect(232, 170, 70, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_channel_9.setFont(font)
        self.l_channel_9.setObjectName(_fromUtf8("l_channel_9"))
        self.cB_subida_1 = QtGui.QCheckBox(self.tab_separados)
        self.cB_subida_1.setGeometry(QtCore.QRect(350, 10, 97, 22))
        self.cB_subida_1.setChecked(True)
        self.cB_subida_1.setObjectName(_fromUtf8("cB_subida_1"))
        self.l_channel_10 = QtGui.QLabel(self.tab_separados)
        self.l_channel_10.setGeometry(QtCore.QRect(232, 250, 70, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_channel_10.setFont(font)
        self.l_channel_10.setObjectName(_fromUtf8("l_channel_10"))
        self.lE_time_3 = QtGui.QLineEdit(self.tab_separados)
        self.lE_time_3.setGeometry(QtCore.QRect(149, 165, 81, 21))
        self.lE_time_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_time_3.setObjectName(_fromUtf8("lE_time_3"))
        self.pW_channel_2 = PlotWidget(self.tab_separados)
        self.pW_channel_2.setGeometry(QtCore.QRect(8, 109, 701, 51))
        self.pW_channel_2.setObjectName(_fromUtf8("pW_channel_2"))
        self.cB_descida_5 = QtGui.QCheckBox(self.tab_separados)
        self.cB_descida_5.setGeometry(QtCore.QRect(460, 325, 100, 22))
        self.cB_descida_5.setObjectName(_fromUtf8("cB_descida_5"))
        self.l_channel_11 = QtGui.QLabel(self.tab_separados)
        self.l_channel_11.setGeometry(QtCore.QRect(232, 330, 70, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_channel_11.setFont(font)
        self.l_channel_11.setObjectName(_fromUtf8("l_channel_11"))
        self.cB_descida_6 = QtGui.QCheckBox(self.tab_separados)
        self.cB_descida_6.setGeometry(QtCore.QRect(460, 405, 100, 22))
        self.cB_descida_6.setObjectName(_fromUtf8("cB_descida_6"))
        self.cB_subida_3 = QtGui.QCheckBox(self.tab_separados)
        self.cB_subida_3.setGeometry(QtCore.QRect(350, 165, 100, 22))
        self.cB_subida_3.setChecked(True)
        self.cB_subida_3.setObjectName(_fromUtf8("cB_subida_3"))
        self.sP_channel_5 = QtGui.QSpinBox(self.tab_separados)
        self.sP_channel_5.setGeometry(QtCore.QRect(78, 326, 61, 21))
        self.sP_channel_5.setMinimum(1)
        self.sP_channel_5.setObjectName(_fromUtf8("sP_channel_5"))
        self.sP_channel_6 = QtGui.QSpinBox(self.tab_separados)
        self.sP_channel_6.setGeometry(QtCore.QRect(78, 406, 61, 21))
        self.sP_channel_6.setMinimum(1)
        self.sP_channel_6.setObjectName(_fromUtf8("sP_channel_6"))
        self.cB_subida_2 = QtGui.QCheckBox(self.tab_separados)
        self.cB_subida_2.setGeometry(QtCore.QRect(350, 86, 100, 22))
        self.cB_subida_2.setChecked(True)
        self.cB_subida_2.setObjectName(_fromUtf8("cB_subida_2"))
        self.sP_channel_1 = QtGui.QSpinBox(self.tab_separados)
        self.sP_channel_1.setGeometry(QtCore.QRect(78, 6, 61, 21))
        self.sP_channel_1.setMinimum(1)
        self.sP_channel_1.setObjectName(_fromUtf8("sP_channel_1"))
        self.cB_descida_4 = QtGui.QCheckBox(self.tab_separados)
        self.cB_descida_4.setGeometry(QtCore.QRect(460, 246, 100, 22))
        self.cB_descida_4.setObjectName(_fromUtf8("cB_descida_4"))
        self.cB_subida_5 = QtGui.QCheckBox(self.tab_separados)
        self.cB_subida_5.setGeometry(QtCore.QRect(350, 325, 100, 22))
        self.cB_subida_5.setChecked(True)
        self.cB_subida_5.setObjectName(_fromUtf8("cB_subida_5"))
        self.pW_channel_6 = PlotWidget(self.tab_separados)
        self.pW_channel_6.setGeometry(QtCore.QRect(8, 429, 701, 51))
        self.pW_channel_6.setObjectName(_fromUtf8("pW_channel_6"))
        self.cB_descida_3 = QtGui.QCheckBox(self.tab_separados)
        self.cB_descida_3.setGeometry(QtCore.QRect(460, 165, 100, 22))
        self.cB_descida_3.setObjectName(_fromUtf8("cB_descida_3"))
        self.cB_subida_6 = QtGui.QCheckBox(self.tab_separados)
        self.cB_subida_6.setGeometry(QtCore.QRect(350, 405, 100, 22))
        self.cB_subida_6.setChecked(True)
        self.cB_subida_6.setObjectName(_fromUtf8("cB_subida_6"))
        self.lE_time_6 = QtGui.QLineEdit(self.tab_separados)
        self.lE_time_6.setGeometry(QtCore.QRect(148, 405, 81, 21))
        self.lE_time_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_time_6.setObjectName(_fromUtf8("lE_time_6"))
        self.lE_time_2 = QtGui.QLineEdit(self.tab_separados)
        self.lE_time_2.setGeometry(QtCore.QRect(149, 85, 81, 21))
        self.lE_time_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_time_2.setObjectName(_fromUtf8("lE_time_2"))
        self.cB_descida_1 = QtGui.QCheckBox(self.tab_separados)
        self.cB_descida_1.setGeometry(QtCore.QRect(460, 10, 97, 22))
        self.cB_descida_1.setObjectName(_fromUtf8("cB_descida_1"))
        self.lE_time_4 = QtGui.QLineEdit(self.tab_separados)
        self.lE_time_4.setGeometry(QtCore.QRect(148, 245, 81, 21))
        self.lE_time_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_time_4.setObjectName(_fromUtf8("lE_time_4"))
        self.pW_channel_1 = PlotWidget(self.tab_separados)
        self.pW_channel_1.setGeometry(QtCore.QRect(8, 29, 701, 51))
        self.pW_channel_1.setObjectName(_fromUtf8("pW_channel_1"))
        self.l_channel_13 = QtGui.QLabel(self.tab_separados)
        self.l_channel_13.setGeometry(QtCore.QRect(230, 90, 70, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.l_channel_13.setFont(font)
        self.l_channel_13.setObjectName(_fromUtf8("l_channel_13"))
        self.tab_views.addTab(self.tab_separados, _fromUtf8(""))
        self.tab_juntos = QtGui.QWidget()
        self.tab_juntos.setObjectName(_fromUtf8("tab_juntos"))
        self.pW_all = PlotWidget(self.tab_juntos)
        self.pW_all.setGeometry(QtCore.QRect(9, 7, 701, 341))
        self.pW_all.setObjectName(_fromUtf8("pW_all"))
        self.tW_timetable = QtGui.QTableWidget(self.tab_juntos)
        self.tW_timetable.setGeometry(QtCore.QRect(182, 360, 528, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tW_timetable.setFont(font)
        self.tW_timetable.setObjectName(_fromUtf8("tW_timetable"))
        self.tW_timetable.setColumnCount(0)
        self.tW_timetable.setRowCount(0)
        self.tW_timetable.horizontalHeader().setDefaultSectionSize(85)
        self.tW_timetable.verticalHeader().setDefaultSectionSize(20)
        self.pB_timetable = QtGui.QPushButton(self.tab_juntos)
        self.pB_timetable.setGeometry(QtCore.QRect(10, 360, 171, 111))
        self.pB_timetable.setObjectName(_fromUtf8("pB_timetable"))
        self.tab_views.addTab(self.tab_juntos, _fromUtf8(""))
        self.cB_constrain = QtGui.QCheckBox(self.tab_mostrador)
        self.cB_constrain.setGeometry(QtCore.QRect(670, 500, 181, 41))
        self.cB_constrain.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.cB_constrain.setObjectName(_fromUtf8("cB_constrain"))
        self.cB_channel_1 = QtGui.QCheckBox(self.tab_mostrador)
        self.cB_channel_1.setGeometry(QtCore.QRect(760, 10, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cB_channel_1.setFont(font)
        self.cB_channel_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(255, 255, 255);"))
        self.cB_channel_1.setChecked(True)
        self.cB_channel_1.setObjectName(_fromUtf8("cB_channel_1"))
        self.cB_channel_2 = QtGui.QCheckBox(self.tab_mostrador)
        self.cB_channel_2.setGeometry(QtCore.QRect(760, 90, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cB_channel_2.setFont(font)
        self.cB_channel_2.setStyleSheet(_fromUtf8("color: rgb(0, 255, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.cB_channel_2.setChecked(True)
        self.cB_channel_2.setObjectName(_fromUtf8("cB_channel_2"))
        self.cB_channel_3 = QtGui.QCheckBox(self.tab_mostrador)
        self.cB_channel_3.setGeometry(QtCore.QRect(760, 170, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cB_channel_3.setFont(font)
        self.cB_channel_3.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.cB_channel_3.setChecked(True)
        self.cB_channel_3.setObjectName(_fromUtf8("cB_channel_3"))
        self.cB_channel_4 = QtGui.QCheckBox(self.tab_mostrador)
        self.cB_channel_4.setGeometry(QtCore.QRect(760, 250, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cB_channel_4.setFont(font)
        self.cB_channel_4.setStyleSheet(_fromUtf8("color: rgb(0, 128, 128);\n"
"background-color: rgb(255, 255, 255);"))
        self.cB_channel_4.setChecked(True)
        self.cB_channel_4.setObjectName(_fromUtf8("cB_channel_4"))
        self.cB_channel_5 = QtGui.QCheckBox(self.tab_mostrador)
        self.cB_channel_5.setGeometry(QtCore.QRect(760, 330, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cB_channel_5.setFont(font)
        self.cB_channel_5.setStyleSheet(_fromUtf8("color: rgb(128, 128, 0);\n"
"background-color: rgb(255, 255, 255);"))
        self.cB_channel_5.setChecked(True)
        self.cB_channel_5.setObjectName(_fromUtf8("cB_channel_5"))
        self.cB_channel_6 = QtGui.QCheckBox(self.tab_mostrador)
        self.cB_channel_6.setGeometry(QtCore.QRect(760, 410, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cB_channel_6.setFont(font)
        self.cB_channel_6.setStyleSheet(_fromUtf8("color: rgb(128, 0, 128);\n"
"background-color: rgb(255, 255, 255);"))
        self.cB_channel_6.setChecked(True)
        self.cB_channel_6.setObjectName(_fromUtf8("cB_channel_6"))
        self.label_8 = QtGui.QLabel(self.tab_mostrador)
        self.label_8.setGeometry(QtCore.QRect(280, 510, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lE_delay = QtGui.QLineEdit(self.tab_mostrador)
        self.lE_delay.setGeometry(QtCore.QRect(390, 510, 71, 21))
        self.lE_delay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lE_delay.setObjectName(_fromUtf8("lE_delay"))
        self.label_9 = QtGui.QLabel(self.tab_mostrador)
        self.label_9.setGeometry(QtCore.QRect(470, 510, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tab_views.raise_()
        self.pB_startacq.raise_()
        self.l_mostrador.raise_()
        self.label_7.raise_()
        self.vS_channel_1.raise_()
        self.lE_channel_1.raise_()
        self.vS_channel_2.raise_()
        self.lE_channel_2.raise_()
        self.lE_channel_5.raise_()
        self.lE_channel_4.raise_()
        self.lE_channel_3.raise_()
        self.lE_channel_6.raise_()
        self.vS_channel_4.raise_()
        self.vS_channel_3.raise_()
        self.vS_channel_5.raise_()
        self.vS_channel_6.raise_()
        self.cB_constrain.raise_()
        self.cB_channel_1.raise_()
        self.cB_channel_2.raise_()
        self.cB_channel_3.raise_()
        self.cB_channel_4.raise_()
        self.cB_channel_5.raise_()
        self.cB_channel_6.raise_()
        self.label_8.raise_()
        self.lE_delay.raise_()
        self.label_9.raise_()
        self.tabPrincipal.addTab(self.tab_mostrador, _fromUtf8(""))
        self.tab_arquivo = QtGui.QWidget()
        self.tab_arquivo.setObjectName(_fromUtf8("tab_arquivo"))
        self.pB_save = QtGui.QPushButton(self.tab_arquivo)
        self.pB_save.setGeometry(QtCore.QRect(20, 70, 391, 27))
        self.pB_save.setObjectName(_fromUtf8("pB_save"))
        self.pB_load = QtGui.QPushButton(self.tab_arquivo)
        self.pB_load.setGeometry(QtCore.QRect(20, 100, 391, 27))
        self.pB_load.setObjectName(_fromUtf8("pB_load"))
        self.pB_savetime = QtGui.QPushButton(self.tab_arquivo)
        self.pB_savetime.setGeometry(QtCore.QRect(430, 70, 391, 27))
        self.pB_savetime.setObjectName(_fromUtf8("pB_savetime"))
        self.tabPrincipal.addTab(self.tab_arquivo, _fromUtf8(""))
        self.tab_serial = QtGui.QWidget()
        self.tab_serial.setObjectName(_fromUtf8("tab_serial"))
        self.pB_connect = QtGui.QPushButton(self.tab_serial)
        self.pB_connect.setGeometry(QtCore.QRect(70, 90, 301, 27))
        self.pB_connect.setObjectName(_fromUtf8("pB_connect"))
        self.label_2 = QtGui.QLabel(self.tab_serial)
        self.label_2.setGeometry(QtCore.QRect(70, 40, 311, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pB_closeconnection = QtGui.QPushButton(self.tab_serial)
        self.pB_closeconnection.setGeometry(QtCore.QRect(70, 210, 171, 27))
        self.pB_closeconnection.setObjectName(_fromUtf8("pB_closeconnection"))
        self.layoutWidget = QtGui.QWidget(self.tab_serial)
        self.layoutWidget.setGeometry(QtCore.QRect(71, 141, 265, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.cB_port = QtGui.QComboBox(self.layoutWidget)
        self.cB_port.setObjectName(_fromUtf8("cB_port"))
        self.horizontalLayout_2.addWidget(self.cB_port)
        self.label_25 = QtGui.QLabel(self.tab_serial)
        self.label_25.setGeometry(QtCore.QRect(70, 270, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.l_commstatus = QtGui.QLabel(self.tab_serial)
        self.l_commstatus.setGeometry(QtCore.QRect(200, 270, 491, 17))
        self.l_commstatus.setObjectName(_fromUtf8("l_commstatus"))
        self.tabPrincipal.addTab(self.tab_serial, _fromUtf8(""))
        self.tab_sobre = QtGui.QWidget()
        self.tab_sobre.setObjectName(_fromUtf8("tab_sobre"))
        self.l_ufscar = QtGui.QLabel(self.tab_sobre)
        self.l_ufscar.setGeometry(QtCore.QRect(160, 370, 180, 125))
        self.l_ufscar.setObjectName(_fromUtf8("l_ufscar"))
        self.l_cca = QtGui.QLabel(self.tab_sobre)
        self.l_cca.setGeometry(QtCore.QRect(567, 368, 130, 122))
        self.l_cca.setObjectName(_fromUtf8("l_cca"))
        self.label_3 = QtGui.QLabel(self.tab_sobre)
        self.label_3.setGeometry(QtCore.QRect(530, 497, 211, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_sobre)
        self.textBrowser.setGeometry(QtCore.QRect(80, 40, 681, 321))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabPrincipal.addTab(self.tab_sobre, _fromUtf8(""))
        self.l_filename = QtGui.QLabel(IRTempus)
        self.l_filename.setGeometry(QtCore.QRect(520, 12, 251, 20))
        self.l_filename.setObjectName(_fromUtf8("l_filename"))

        self.retranslateUi(IRTempus)
        self.tabPrincipal.setCurrentIndex(0)
        self.tab_views.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(IRTempus)

    def retranslateUi(self, IRTempus):
        IRTempus.setWindowTitle(_translate("IRTempus", "IRTempus", None))

        self.tab_mostrador.setToolTip(_translate("IRTempus", "<html><head/><body><p>Прикажете аквизиција на податоци.</p></body></html>", None))
        self.pB_startacq.setToolTip(_translate("IRTempus", "<html><head/><body><p>Започнете и запрете го отчитувањето на податоци.</p></body></html>", None))
        self.pB_startacq.setText(_translate("IRTempus", "Старт", None))
        self.l_mostrador.setText(_translate("IRTempus", "стопирана", None))
        self.label_7.setText(_translate("IRTempus", "Статус на аквизиција:", None))
        self.vS_channel_1.setToolTip(_translate("IRTempus", "<html><head/><body><p>Референтна вредност на временски интервал за активирање на Канал 1</p></body></html>", None))
        self.lE_channel_1.setToolTip(_translate("IRTempus", "<html><head/><body><p>Референтна вредност на временски интервал за активирање на Канал 1</p></body></html>", None))
        self.lE_channel_1.setText(_translate("IRTempus", "512", None))
        self.vS_channel_2.setToolTip(_translate("IRTempus", "<html><head/><body><p>Референтна вредност на временски интервал за активирање на Канал 2</p></body></html>", None))
        self.lE_channel_2.setText(_translate("IRTempus", "512", None))
        self.lE_channel_5.setText(_translate("IRTempus", "512", None))
        self.lE_channel_4.setText(_translate("IRTempus", "512", None))
        self.lE_channel_3.setText(_translate("IRTempus", "512", None))
        self.lE_channel_6.setText(_translate("IRTempus", "512", None))
        self.vS_channel_4.setToolTip(_translate("IRTempus", "<html><head/><body><p>Референтна вредност на временски интервал за активирање на Канал 3</p></body></html>", None))
        self.vS_channel_3.setToolTip(_translate("IRTempus", "<html><head/><body><p>Референтна вредност на временски интервал за активирање на Канал 4</p></body></html>", None))
        self.vS_channel_5.setToolTip(_translate("IRTempus", "<html><head/><body><p>Референтна вредност на временски интервал за активирање на Канал 5</p></body></html>", None))
        self.vS_channel_6.setToolTip(_translate("IRTempus", "<html><head/><body><p>Референтна вредност на временски интервал за активирање на Канал 6</p></body></html>", None))
        self.sP_channel_4.setToolTip(_translate("IRTempus", "<html><head/><body><p>Избришете ги вредностите на временските интервали добиени од каналите.</p></body></html>", None))
        self.lE_time_1.setToolTip(_translate("IRTempus", "<html><head/><body><p>Време на активирање на каналите.</p></body></html>", None))
        self.lE_time_1.setText(_translate("IRTempus", "0", None))
        self.sP_channel_2.setToolTip(_translate("IRTempus", "<html><head/><body><p>Избришете ги вредностите на временските интервали добиени со активирање на каналите.</p></body></html>", None))
        self.lE_time_5.setToolTip(_translate("IRTempus", "<html><head/><body><p>Време на активирање на каналите.</p></body></html>", None))
        self.lE_time_5.setText(_translate("IRTempus", "0", None))
        self.cB_subida_4.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на порастот на референтните вредности.</p></body></html>", None))
        self.cB_subida_4.setText(_translate("IRTempus", "Пораст", None))
        self.cB_descida_2.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на падот на референтните вредности.</p></body></html>", None))
        self.cB_descida_2.setText(_translate("IRTempus", "Пад", None))
        self.l_channel_8.setText(_translate("IRTempus", "секунди", None))
        self.sP_channel_3.setToolTip(_translate("IRTempus", "<html><head/><body><p>Избришете ги вредностите на временските интервали добиени со активирање на каналите.</p></body></html>", None))
        self.l_channel_12.setText(_translate("IRTempus", "секунди", None))
        self.l_channel_9.setText(_translate("IRTempus", "секунди", None))
        self.cB_subida_1.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на порастот на референтните вредности.</p></body></html>", None))
        self.cB_subida_1.setText(_translate("IRTempus", "Пораст", None))
        self.l_channel_10.setText(_translate("IRTempus", "секунди", None))
        self.lE_time_3.setToolTip(_translate("IRTempus", "<html><head/><body><p>Време на активирање на каналите.</p></body></html>", None))
        self.lE_time_3.setText(_translate("IRTempus", "0", None))
        self.cB_descida_5.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на падот на референтните вредности.</p></body></html>", None))
        self.cB_descida_5.setText(_translate("IRTempus", "Пад", None))
        self.l_channel_11.setText(_translate("IRTempus", "секунди", None))
        self.cB_descida_6.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на падот на референтните вредности.</p></body></html>", None))
        self.cB_descida_6.setText(_translate("IRTempus", "Пад", None))
        self.cB_subida_3.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на падот на референтните вредности.</p></body></html>", None))
        self.cB_subida_3.setText(_translate("IRTempus", "Пораст", None))
        self.sP_channel_5.setToolTip(_translate("IRTempus", "<html><head/><body><p>Време на активирање на каналите.</p></body></html>", None))
        self.sP_channel_6.setToolTip(_translate("IRTempus", "<html><head/><body><p>Време на активирање на каналите.</p></body></html>", None))
        self.cB_subida_2.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на порастот на референтните вредности.</p></body></html>", None))
        self.cB_subida_2.setText(_translate("IRTempus", "Пораст", None))
        self.sP_channel_1.setToolTip(_translate("IRTempus", "<html><head/><body><p>Време на активирање на каналите.</p></body></html>", None))
        self.cB_descida_4.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на падот на референтните вредности.</p></body></html>", None))
        self.cB_descida_4.setText(_translate("IRTempus", "Пад", None))
        self.cB_descida_3.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на падот на референтните вредности.</p></body></html>", None))
        self.cB_subida_5.setText(_translate("IRTempus", "Пораст", None))
        self.cB_descida_3.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на падот на референтните вредности.</p></body></html>", None))
        self.cB_descida_3.setText(_translate("IRTempus", "Пад", None))
        self.cB_subida_6.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на порастот на референтните вредности.</p></body></html>", None))
        self.cB_subida_6.setText(_translate("IRTempus", "Пораст", None))
        self.lE_time_6.setToolTip(_translate("IRTempus", "<html><head/><body><p>Време на активирање на каналите.</p></body></html>", None))
        self.lE_time_6.setText(_translate("IRTempus", "0", None))
        self.lE_time_2.setToolTip(_translate("IRTempus", "<html><head/><body><p>Време на активирање на каналите.</p></body></html>", None))
        self.lE_time_2.setText(_translate("IRTempus", "0", None))
        self.cB_descida_1.setToolTip(_translate("IRTempus", "<html><head/><body><p>Означете ги временските интервали за активирање на каналите во однос на падот на референтните вредности.</p></body></html>", None))
        self.cB_descida_1.setText(_translate("IRTempus", "Пад", None))
        self.lE_time_4.setToolTip(_translate("IRTempus", "<html><head/><body><p>Време на активирање на каналите.</p></body></html>", None))
        self.lE_time_4.setText(_translate("IRTempus", "0", None))
        self.l_channel_13.setText(_translate("IRTempus", "секунди", None))
        self.tab_views.setTabText(self.tab_views.indexOf(self.tab_separados), _translate("IRTempus", "Поединечен Приказ", None))
        self.pW_all.setToolTip(_translate("IRTempus", "<html><head/><body><p>График на земање примероци (семплирање) од шест канали во кои ординатата (ограничена во опсегот од 0 до 1023) е пропорционална на напонот измерен  на респективните системи на канали составени од инфрацрвени сетила(пар од инфрацрвена светлечка диода(LED) и инфрацрвен фото-транзистор), а апсцисата одговара на времето во измерено во секунди.</p></body></html>", None))
        self.tW_timetable.setToolTip(_translate("IRTempus", "<html><head/><body><p><span style=\" font-weight:400;\">Табелата на временските интервали измерени во секунди при активирањето на селектираните канали. Позитивните временски интервали одговараат на порастот, а негативните на падот на графикот на функцијата.</span></p></body></html>", None))
        self.pB_timetable.setToolTip(_translate("IRTempus", "<html><head/><body><p>Се прави табела на активирање на каналите за временските интервали за порастот и / или падот според референтните нивоа на секој канал соодветно.</p></body></html>", None))
        self.pB_timetable.setText(_translate("IRTempus", "Прикажи временски\n"
"интервали потребни\n"
"за премин низ сети -\n"
" лата, односно време\n"
" на нивна активација.", None))
        self.tab_views.setTabText(self.tab_views.indexOf(self.tab_juntos), _translate("IRTempus", "Целосен Приказ", None))
        self.cB_constrain.setToolTip(_translate("IRTempus", "<html><head/><body><p>Канал 1 како референтен за останатите канали.</p></body></html>", None))
        self.cB_constrain.setText(_translate("IRTempus", "Канал 1 како реф.\n"
"за останатите канали", None))
        self.cB_channel_1.setText(_translate("IRTempus", "Канал 1", None))
        self.cB_channel_2.setText(_translate("IRTempus", "Канал 2", None))
        self.cB_channel_3.setText(_translate("IRTempus", "Канал 3", None))
        self.cB_channel_4.setText(_translate("IRTempus", "Канал 4", None))
        self.cB_channel_5.setText(_translate("IRTempus", "Канал 5", None))
        self.cB_channel_6.setText(_translate("IRTempus", "Канал 6", None))
        self.label_8.setToolTip(_translate("IRTempus", "<html><head/><body><p>Дополнително одложување помеѓу секоја аквизиција (0 до 65535 ms).</p></body></html>", None))
        self.label_8.setText(_translate("IRTempus", "Одложување:", None))
        self.lE_delay.setToolTip(_translate("IRTempus", "<html><head/><body><p>Дополнително одложување помеѓу секоја аквизиција (0 до 65535 ms).</p></body></html>", None))
        self.lE_delay.setText(_translate("IRTempus", "0", None))
        self.label_9.setText(_translate("IRTempus", "ms", None))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tab_mostrador), _translate("IRTempus", "Прикажи", None))
        self.pB_save.setToolTip(_translate("IRTempus", "<html><head/><body><p>Зачувајте датотека со целосни бранови облици од сите канали.</p></body></html>", None))
        self.pB_save.setText(_translate("IRTempus", "Зачувај датотека на график со сите бранови облици", None))
        self.pB_load.setToolTip(_translate("IRTempus", "<html><head/><body><p>Прочитајте датотека со целосни бранови облици од сите канали</p></body></html>", None))
        self.pB_load.setText(_translate("IRTempus", "Прочитај датотека на график со сите бранови облици", None))
        self.pB_savetime.setToolTip(_translate("IRTempus", "<html><head/><body><p>Зачувуваjте датотека со временските интервали на активирањето на избраните канали според временската табела (табелата на времињата).</p></body></html>", None))
        self.pB_savetime.setText(_translate("IRTempus", "Зачувај табела на измерени временски интервали", None))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tab_arquivo), _translate("IRTempus", "Датотека", None))
        self.pB_connect.setToolTip(_translate("IRTempus", "<html><head/><body><p>Автоматски изберете го серискиот порт на кој е поврзана плочата Arduino.</p></body></html>", None))
        self.pB_connect.setText(_translate("IRTempus", "Автоматска селекција на сериска порта", None))
        self.label_2.setText(_translate("IRTempus", "Сериска комуникација со Arduino", None))
        self.pB_closeconnection.setToolTip(_translate("IRTempus", "<html><head/><body><p>Да се прекине поврзувањето со плочата Arduino.</p></body></html>", None))
        self.pB_closeconnection.setText(_translate("IRTempus", "Прекини комуникација", None))
        self.label.setText(_translate("IRTempus", "Листа на порти:", None))
        self.cB_port.setToolTip(_translate("IRTempus", "<html><head/><body><p>Изберете од листата на сериски порти на која е поврзана плочата Arduino.</p></body></html>", None))
        self.label_25.setText(_translate("IRTempus", "Комуникација:", None))
        self.l_commstatus.setText(_translate("IRTempus", "не започната", None))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tab_serial), _translate("IRTempus", "Комуникација", None))
        self.l_ufscar.setText(_translate("IRTempus", "TextLabel", None))
        self.l_cca.setText(_translate("IRTempus", "TextLabel", None))
        self.label_3.setText(_translate("IRTempus", "ФЕИТ - Институт за физика", None))
        self.textBrowser.setHtml(_translate("IRTempus", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tabPrincipal.setTabText(self.tabPrincipal.indexOf(self.tab_sobre), _translate("IRTempus", "Повеќе", None))
        self.l_filename.setToolTip(_translate("IRTempus", "<html><head/><body><p>Последна зачувана или прочитана датотека. Ѕвездичката на почетокот покажува дека последната аквизиција сè уште не е зачувана (снимена).</p></body></html>", None))
        self.l_filename.setText(_translate("IRTempus", "*Датотека:", None))

from pyqtgraph import PlotWidget
